# Generated by Django 5.2.7 on 2025-10-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
