# Generated by Django 5.2.7 on 2025-11-12 01:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_votante_fecha_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'puestos',
            },
        ),
        migrations.AddField(
            model_name='votante',
            name='asistio',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='votante',
            name='zonificado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricalVotante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField(null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('zonificado', models.BooleanField(default=False)),
                ('asistio', models.BooleanField(null=True)),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('actualizado', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.mesa')),
            ],
            options={
                'verbose_name': 'historical votante',
                'verbose_name_plural': 'historical votantes',
                'db_table': 'log_votantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='votante',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.mesa'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.puesto'),
        ),
    ]
