# Generated by Django 5.2.7 on 2025-11-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='identificacion',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
