# Generated by Django 5.2.7 on 2025-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userconfig_meta_alter_userconfig_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvotante',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='votante',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='historicalvotante',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalvotante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='votante',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='votante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
