# Generated by Django 5.2.7 on 2025-11-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_historicalvotante_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.AlterField(
            model_name='votante',
            name='mesa',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalvotante',
            name='mesa',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvotante',
            name='puesto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.puesto'),
        ),
        migrations.AddField(
            model_name='votante',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.puesto'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.departamento')),
            ],
            options={
                'db_table': 'municipios',
            },
        ),
        migrations.AddField(
            model_name='puesto',
            name='municipio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='core.municipio'),
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
