# Generated by Django 5.2.7 on 2025-11-12 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_departamento_alter_votante_mesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='municipio',
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.municipio')),
            ],
            options={
                'db_table': 'comunas',
            },
        ),
        migrations.AddField(
            model_name='puesto',
            name='comuna',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='core.comuna'),
        ),
    ]
