# Generated by Django 5.2.7 on 2025-11-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_puesto_municipio_comuna_puesto_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvotante',
            name='referido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='votante',
            name='referido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
