# Generated by Django 5.2.7 on 2025-11-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historicalvotante_referido_votante_referido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvotante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='votante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
