# Generated by Django 5.2.7 on 2025-11-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_historicalvotante_email_alter_votante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.municipio'),
        ),
    ]
