# Generated by Django 5.2.7 on 2025-11-18 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userconfig_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvotante',
            name='municipio',
            field=models.ForeignKey(blank=True, db_constraint=False, default='54001', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.municipio'),
        ),
        migrations.AddField(
            model_name='votante',
            name='municipio',
            field=models.ForeignKey(default='54001', on_delete=django.db.models.deletion.RESTRICT, to='core.municipio'),
        ),
    ]
