# Generated by Django 5.2.7 on 2025-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalvotante_municipio_votante_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='municipio',
            name='meta',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
