# Generated by Django 5.2.7 on 2025-12-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_municipio_options_municipio_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together={('nombre', 'comuna')},
        ),
    ]
