# Generated by Django 5.2.7 on 2026-01-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_metausuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'ordering': ['comuna__municipio__nombre', 'nombre']},
        ),
        migrations.AddField(
            model_name='puesto',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.municipio'),
        ),
    ]
