# Generated by Django 5.2.7 on 2026-01-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_puesto_options_puesto_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'ordering': ['municipio__nombre', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='municipio',
        ),
        migrations.AddField(
            model_name='historicalvotante',
            name='masivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votante',
            name='masivo',
            field=models.BooleanField(default=False),
        ),
    ]
