# Generated by Django 5.2.7 on 2026-02-10 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_puesto_options_remove_userconfig_municipio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='orientador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orientador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votante',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.puesto'),
        ),
    ]
