# Generated by Django 5.2.7 on 2026-03-07 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userconfig_orientador_alter_votante_puesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipos_asistencias',
            },
        ),
        migrations.CreateModel(
            name='LogAsistenciaVotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.votante')),
                ('tipo_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.tipoasistencia')),
            ],
            options={
                'db_table': 'log_asistencias_votantes',
            },
        ),
        migrations.AddField(
            model_name='historicalvotante',
            name='tipo_asistencia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tipoasistencia'),
        ),
        migrations.AddField(
            model_name='votante',
            name='tipo_asistencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.tipoasistencia'),
        ),
    ]
