# Generated by Django 5.2.7 on 2026-03-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tipoasistencia_logasistenciavotante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='habilitado_consulta',
            field=models.BooleanField(default=False),
        ),
    ]
